version: '3'
services:
  db:
    # image: postgres:11.1
    image: mysql:5.7.23
    env_file: .env
    volumes:
      # - ./psql-data:/var/lib/pgsql
      - ./mysql-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    env_file:
      - .sec_env
      - .env
    command: bundle exec rails s -p 8081 -b '0.0.0.0'
    environment:
      - APP_URL=http://localhost/
      - APP_NAME=一日一善
    volumes:
      - .:/myapp
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  db-data:
    driver: local
