apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: itizen-setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
        - name: setup
          image: kter/itinitiitizen:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "bundle exec rake db:create && bundle exec rake db:migrate"]
          env:
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: APP_NAME
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: APP_URL
            - name: ITIZEN_DB_USER
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: DB_USER
            - name: ITIZEN_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: DB_PASS
            - name: ITIZEN_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: DB_HOST
            - name: ITIZEN_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: DB_PORT
            - name: RAILS_ENV
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: RAILS_ENV
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: SECRET_KEY_BASE
      restartPolicy: Never
