apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
        - name: setup
          image: kter/itinitiitizen:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "bundle exec rake db:create && bundle exec rake db:migrate"]
          envFrom:
            - configMapRef:
                name: rails-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DB_PORT
            - name: RAILS_ENV
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: RAILS_ENV
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: SECRET_KEY_BASE
      restartPolicy: Never
