apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: external-lb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - itizen.tomohiko.io
    secretName: ingress-tls
  rules:
    - host: itizen.tomohiko.io
      http:
        paths:
          - path: /
            backend:
              serviceName: itizen-web
              servicePort: 3000
