apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: external-lb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: itizen.tomohiko.io
      http:
        paths:
          - path: /
            backend:
              serviceName: itizen-web
              servicePort: 3000
