apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: itizen-web
spec:
  selector:
    app: itizen-app
  type: ClusterIP
  ports:
    - name: "itizen-port"
      protocol: "TCP"
      port: 3000
      targetPort: 3000
  #type: NodePort
  #ports:
  #  - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: itizen-app
spec:
  selector:
    matchLabels:
      app: itizen-app
  template:
    metadata:
      labels:
        app: itizen-app
    spec:
      containers:
        - name: itizen
          image: kter/itinitiitizen:latest
          imagePullPolicy: Always
          command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
          env:
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: APP_NAME
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: APP_URL
            - name: ITIZEN_DB_USER
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: DB_USER
            - name: ITIZEN_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: DB_PASS
            - name: ITIZEN_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: DB_HOST
            - name: ITIZEN_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: DB_NAME
            - name: ITIZEN_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: DB_PORT
            - name: RAILS_ENV
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: RAILS_ENV
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: SECRET_KEY_BASE

            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: GCP_PROJECT_ID
            - name: GCP_PRIVATE_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: GCP_PRIVATE_KEY_ID
            - name: GCP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: GCP_PRIVATE_KEY
            - name: GCP_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: GCP_CLIENT_EMAIL
            - name: GCP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: GCP_CLIENT_ID
            - name: GCP_CLIENT_X509_CERT_URL
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: GCP_CLIENT_X509_CERT_URL
            - name: GOOGLE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: GOOGLE_APP_ID
            - name: GOOGLE_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: itizen-credentials
                  key: GOOGLE_APP_SECRET
          ports:
            - containerPort: 3000
